### ISSUE TITLE
post-link failure on OS-X

### ISSUE THREAD

**Issue by ijstokes** [conda-forge/ipyparallel-feedstock#8]
I think the trace tells the story.  I'm trying to create a new Conda environment from scratch, and it includes things (Jupyter, I suppose) which have ipyparallel as a dependency.  The post-link step fails.

``` bash
$ conda create -n pypar -c conda-forge ipyparallel ujson dask distributed bokeh scikit-learn pytables jupyter snakeviz dask distributed

Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /Users/ijstokes/anaconda/envs/pypar:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-3.0.0          |                0         465 KB  conda-forge
    yaml-0.1.6                 |                0          82 KB  conda-forge
    zlib-1.2.8                 |                3          90 KB  conda-forge
    hdf5-1.8.17                |                2         3.4 MB  conda-forge
    libpng-1.6.23              |                0         319 KB  conda-forge
    openblas-0.2.18            |                4        16.5 MB  conda-forge
    blas-1.1                   |         openblas           1 KB  conda-forge
    freetype-2.6.3             |                1         782 KB  conda-forge
    python-2.7.12              |                0        10.8 MB  conda-forge
    click-6.6                  |           py27_0          97 KB  conda-forge
    cloudpickle-0.2.1          |           py27_2          17 KB  conda-forge
    decorator-4.0.10           |           py27_0          12 KB  conda-forge
    docutils-0.12              |           py27_0         637 KB  conda-forge
    jmespath-0.9.0             |           py27_0          28 KB  conda-forge
    locket-0.2.0               |           py27_0           5 KB  conda-forge
    msgpack-python-0.4.7       |           py27_0          72 KB
    numpy-1.11.1               |py27_blas_openblas_201         3.2 MB  conda-forge
    psutil-4.3.0               |           py27_0         217 KB  conda-forge
    ptyprocess-0.5.1           |           py27_0          19 KB  conda-forge
    pytz-2016.6.1              |           py27_0         183 KB  conda-forge
    pyyaml-3.11                |           py27_0         142 KB  conda-forge
    pyzmq-15.4.0               |           py27_0         348 KB  conda-forge
    requests-2.10.0            |           py27_0         610 KB  conda-forge
    sip-4.18                   |           py27_0         245 KB  conda-forge
    six-1.10.0                 |           py27_0          18 KB  conda-forge
    tblib-1.3.0                |           py27_0          12 KB
    toolz-0.8.0                |           py27_0          77 KB  conda-forge
    ujson-1.35                 |           py27_0          20 KB
    jsonschema-2.5.1           |           py27_0          70 KB  conda-forge
    numexpr-2.6.1              |      np111py27_0         110 KB
    partd-0.3.5                |           py27_0          25 KB  conda-forge
    pathlib2-2.1.0             |           py27_0          26 KB  conda-forge
    pyqt-4.11.4                |           py27_4         4.0 MB
    python-dateutil-2.5.3      |           py27_0         236 KB  conda-forge
    scipy-0.18.0               |np111py27_blas_openblas_201        13.4 MB  conda-forge
    setuptools-25.1.6          |           py27_0         316 KB  conda-forge
    botocore-1.4.41            |           py27_0         1.8 MB  conda-forge
    entrypoints-0.2.2          |           py27_0           6 KB  conda-forge
    jinja2-2.8                 |           py27_1         265 KB  conda-forge
    jupyter_core-4.1.1         |           py27_0          51 KB  conda-forge
    pandas-0.18.1              |      np111py27_1         7.4 MB  conda-forge
    pygments-2.1.3             |           py27_1         1.2 MB  conda-forge
    pytables-3.2.3.1           |      np111py27_0         1.7 MB
    scikit-learn-0.17.1        |np111py27_blas_openblas_201         3.8 MB  conda-forge
    wheel-0.29.0               |           py27_0          81 KB  conda-forge
    bokeh-0.12.1               |           py27_0         3.2 MB
    boto3-1.3.1                |           py27_0          95 KB
    jupyter_client-4.3.0       |           py27_0          96 KB  conda-forge
    pip-8.1.2                  |           py27_0         1.5 MB  conda-forge
    prompt_toolkit-1.0.5       |           py27_0         305 KB  conda-forge
    snakeviz-0.4.1             |           py27_0         148 KB
    terminado-0.6              |           py27_0          18 KB  conda-forge
    ipython-5.0.0              |           py27_1         953 KB  conda-forge
    nbconvert-4.2.0            |           py27_0         310 KB  conda-forge
    s3fs-0.0.6                 |           py27_0          22 KB  conda-forge
    ipykernel-4.4.1            |           py27_0         122 KB
    ipyparallel-5.1.1          |           py27_2         273 KB  conda-forge
    jupyter_console-5.0.0      |           py27_0          28 KB  conda-forge
    qtconsole-4.2.1            |           py27_0         133 KB  conda-forge
    ipywidgets-5.2.2           |           py27_0          59 KB  conda-forge
    dask-0.10.2                |           py27_0         570 KB  conda-forge
    distributed-1.11.3         |           py27_0         284 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        80.7 MB

The following NEW packages will be INSTALLED:

    appnope:                            0.1.0-py27_0                                  
    backports:                          1.0-py27_0                                    
    backports.shutil_get_terminal_size: 1.0.0-py27_0                       conda-forge
    backports_abc:                      0.4-py27_0                         conda-forge
    blas:                               1.1-openblas                       conda-forge
    bokeh:                              0.12.1-py27_0                                 
    boto3:                              1.3.1-py27_0                                  
    botocore:                           1.4.41-py27_0                      conda-forge
    ca-certificates:                    2016.8.2-3                         conda-forge
    certifi:                            2016.8.2-py27_0                    conda-forge
    click:                              6.6-py27_0                         conda-forge
    cloudpickle:                        0.2.1-py27_2                       conda-forge
    configparser:                       3.5.0-py27_0                                  
    dask:                               0.10.2-py27_0                      conda-forge
    decorator:                          4.0.10-py27_0                      conda-forge
    distributed:                        1.11.3-py27_0                      conda-forge
    docutils:                           0.12-py27_0                        conda-forge
    entrypoints:                        0.2.2-py27_0                       conda-forge
    freetype:                           2.6.3-1                            conda-forge
    functools32:                        3.2.3.2-py27_1                     conda-forge
    futures:                            3.0.5-py27_0                                  
    hdf5:                               1.8.17-2                           conda-forge
    ipykernel:                          4.4.1-py27_0                                  
    ipyparallel:                        5.1.1-py27_2                       conda-forge
    ipython:                            5.0.0-py27_1                       conda-forge
    ipython_genutils:                   0.1.0-py27_0                       conda-forge
    ipywidgets:                         5.2.2-py27_0                       conda-forge
    jinja2:                             2.8-py27_1                         conda-forge
    jmespath:                           0.9.0-py27_0                       conda-forge
    jsonschema:                         2.5.1-py27_0                       conda-forge
    jupyter:                            1.0.0-py27_3                                  
    jupyter_client:                     4.3.0-py27_0                       conda-forge
    jupyter_console:                    5.0.0-py27_0                       conda-forge
    jupyter_core:                       4.1.1-py27_0                       conda-forge
    libgfortran:                        3.0.0-0                            conda-forge
    libpng:                             1.6.23-0                           conda-forge
    libsodium:                          1.0.10-0                           conda-forge
    locket:                             0.2.0-py27_0                       conda-forge
    markupsafe:                         0.23-py27_0                        conda-forge
    mistune:                            0.7.3-py27_0                       conda-forge
    mkl:                                11.3.3-0                                      
    msgpack-python:                     0.4.7-py27_0                                  
    nbconvert:                          4.2.0-py27_0                       conda-forge
    nbformat:                           4.0.1-py27_0                       conda-forge
    ncurses:                            5.9-8                              conda-forge
    notebook:                           4.2.2-py27_0                       conda-forge
    numexpr:                            2.6.1-np111py27_0                             
    numpy:                              1.11.1-py27_blas_openblas_201      conda-forge [blas_openblas]
    openblas:                           0.2.18-4                           conda-forge
    openssl:                            1.0.2h-2                           conda-forge
    pandas:                             0.18.1-np111py27_1                 conda-forge
    partd:                              0.3.5-py27_0                       conda-forge
    pathlib2:                           2.1.0-py27_0                       conda-forge
    pexpect:                            4.2.0-py27_1                       conda-forge
    pickleshare:                        0.7.3-py27_0                       conda-forge
    pip:                                8.1.2-py27_0                       conda-forge
    prompt_toolkit:                     1.0.5-py27_0                       conda-forge
    psutil:                             4.3.0-py27_0                       conda-forge
    ptyprocess:                         0.5.1-py27_0                       conda-forge
    pygments:                           2.1.3-py27_1                       conda-forge
    pyqt:                               4.11.4-py27_4                                 
    pytables:                           3.2.3.1-np111py27_0                           
    python:                             2.7.12-0                           conda-forge
    python-dateutil:                    2.5.3-py27_0                       conda-forge
    python.app:                         1.2-py27_4                                    
    pytz:                               2016.6.1-py27_0                    conda-forge
    pyyaml:                             3.11-py27_0                        conda-forge
    pyzmq:                              15.4.0-py27_0                      conda-forge
    qt:                                 4.8.7-4                                       
    qtconsole:                          4.2.1-py27_0                       conda-forge
    readline:                           6.2-0                              conda-forge
    requests:                           2.10.0-py27_0                      conda-forge
    s3fs:                               0.0.6-py27_0                       conda-forge
    scikit-learn:                       0.17.1-np111py27_blas_openblas_201 conda-forge [blas_openblas]
    scipy:                              0.18.0-np111py27_blas_openblas_201 conda-forge [blas_openblas]
    setuptools:                         25.1.6-py27_0                      conda-forge
    simplegeneric:                      0.8.1-py27_0                       conda-forge
    singledispatch:                     3.4.0.3-py27_0                     conda-forge
    sip:                                4.18-py27_0                        conda-forge
    six:                                1.10.0-py27_0                      conda-forge
    snakeviz:                           0.4.1-py27_0                                  
    sqlite:                             3.13.0-1                           conda-forge
    ssl_match_hostname:                 3.5.0.1-py27_0                     conda-forge
    tblib:                              1.3.0-py27_0                                  
    terminado:                          0.6-py27_0                         conda-forge
    tk:                                 8.5.19-0                           conda-forge
    toolz:                              0.8.0-py27_0                       conda-forge
    tornado:                            4.4.1-py27_1                       conda-forge
    traitlets:                          4.2.2-py27_0                       conda-forge
    ujson:                              1.35-py27_0                                   
    wcwidth:                            0.1.7-py27_0                       conda-forge
    wheel:                              0.29.0-py27_0                      conda-forge
    widgetsnbextension:                 1.2.6-py27_3                       conda-forge
    yaml:                               0.1.6-0                            conda-forge
    zeromq:                             4.1.5-0                            conda-forge
    zlib:                               1.2.8-3                            conda-forge

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
libgfortran-3. 100% |############################################################################################| Time: 0:00:00 934.84 kB/s
yaml-0.1.6-0.t 100% |############################################################################################| Time: 0:00:00 548.77 kB/s
zlib-1.2.8-3.t 100% |############################################################################################| Time: 0:00:00 400.65 kB/s
hdf5-1.8.17-2. 100% |############################################################################################| Time: 0:00:01   3.01 MB/s
libpng-1.6.23- 100% |############################################################################################| Time: 0:00:00 659.22 kB/s
openblas-0.2.1 100% |############################################################################################| Time: 0:00:04   3.53 MB/s
blas-1.1-openb 100% |############################################################################################| Time: 0:00:00 649.60 kB/s
freetype-2.6.3 100% |############################################################################################| Time: 0:00:00   1.31 MB/s
python-2.7.12- 100% |############################################################################################| Time: 0:00:03   3.65 MB/s
click-6.6-py27 100% |############################################################################################| Time: 0:00:00 383.25 kB/s
cloudpickle-0. 100% |############################################################################################| Time: 0:00:00 234.22 kB/s
decorator-4.0. 100% |############################################################################################| Time: 0:00:00   3.86 MB/s
docutils-0.12- 100% |############################################################################################| Time: 0:00:00   1.03 MB/s
jmespath-0.9.0 100% |############################################################################################| Time: 0:00:00 380.69 kB/s
locket-0.2.0-p 100% |############################################################################################| Time: 0:00:00   2.42 MB/s
msgpack-python 100% |############################################################################################| Time: 0:00:00 329.87 kB/s
numpy-1.11.1-p 100% |############################################################################################| Time: 0:00:00   3.39 MB/s
psutil-4.3.0-p 100% |############################################################################################| Time: 0:00:00 726.38 kB/s
ptyprocess-0.5 100% |############################################################################################| Time: 0:00:00 254.74 kB/s
pytz-2016.6.1- 100% |############################################################################################| Time: 0:00:00 609.33 kB/s
pyyaml-3.11-py 100% |############################################################################################| Time: 0:00:00 476.06 kB/s
pyzmq-15.4.0-p 100% |############################################################################################| Time: 0:00:00 750.08 kB/s
requests-2.10. 100% |############################################################################################| Time: 0:00:00   1.16 MB/s
sip-4.18-py27_ 100% |############################################################################################| Time: 0:00:00 647.28 kB/s
six-1.10.0-py2 100% |############################################################################################| Time: 0:00:00 239.06 kB/s
tblib-1.3.0-py 100% |############################################################################################| Time: 0:00:00   5.09 MB/s
toolz-0.8.0-py 100% |############################################################################################| Time: 0:00:00 338.40 kB/s
ujson-1.35-py2 100% |############################################################################################| Time: 0:00:00 272.58 kB/s
jsonschema-2.5 100% |############################################################################################| Time: 0:00:00 460.34 kB/s
numexpr-2.6.1- 100% |############################################################################################| Time: 0:00:00 479.31 kB/s
partd-0.3.5-py 100% |############################################################################################| Time: 0:00:00 323.06 kB/s
pathlib2-2.1.0 100% |############################################################################################| Time: 0:00:00 357.57 kB/s
pyqt-4.11.4-py 100% |############################################################################################| Time: 0:00:02   1.63 MB/s
python-dateuti 100% |############################################################################################| Time: 0:00:00 778.30 kB/s
scipy-0.18.0-n 100% |############################################################################################| Time: 0:00:04   3.45 MB/s
setuptools-25. 100% |############################################################################################| Time: 0:00:00 707.26 kB/s
botocore-1.4.4 100% |############################################################################################| Time: 0:00:00   1.96 MB/s
entrypoints-0. 100% |############################################################################################| Time: 0:00:00   3.22 MB/s
jinja2-2.8-py2 100% |############################################################################################| Time: 0:00:00 709.95 kB/s
jupyter_core-4 100% |############################################################################################| Time: 0:00:00 345.20 kB/s
pandas-0.18.1- 100% |############################################################################################| Time: 0:00:01   4.18 MB/s
pygments-2.1.3 100% |############################################################################################| Time: 0:00:00   1.67 MB/s
pytables-3.2.3 100% |############################################################################################| Time: 0:00:06 255.74 kB/s
scikit-learn-0 100% |############################################################################################| Time: 0:00:01   2.94 MB/s
wheel-0.29.0-p 100% |############################################################################################| Time: 0:00:00 534.80 kB/s
bokeh-0.12.1-p 100% |############################################################################################| Time: 0:00:02   1.26 MB/s
boto3-1.3.1-py 100% |############################################################################################| Time: 0:00:00 406.71 kB/s
jupyter_client 100% |############################################################################################| Time: 0:00:00 436.92 kB/s
pip-8.1.2-py27 100% |############################################################################################| Time: 0:00:00   2.20 MB/s
prompt_toolkit 100% |############################################################################################| Time: 0:00:00 817.77 kB/s
snakeviz-0.4.1 100% |############################################################################################| Time: 0:00:00 480.27 kB/s
terminado-0.6- 100% |############################################################################################| Time: 0:00:00 234.91 kB/s
ipython-5.0.0- 100% |############################################################################################| Time: 0:00:00   1.20 MB/s
nbconvert-4.2. 100% |############################################################################################| Time: 0:00:00 697.60 kB/s
s3fs-0.0.6-py2 100% |############################################################################################| Time: 0:00:00 294.18 kB/s
ipykernel-4.4. 100% |############################################################################################| Time: 0:00:00 415.19 kB/s
ipyparallel-5. 100% |############################################################################################| Time: 0:00:00 727.80 kB/s
jupyter_consol 100% |############################################################################################| Time: 0:00:00 383.55 kB/s
qtconsole-4.2. 100% |############################################################################################| Time: 0:00:00 431.85 kB/s
ipywidgets-5.2 100% |############################################################################################| Time: 0:00:00 353.02 kB/s
dask-0.10.2-py 100% |############################################################################################| Time: 0:00:00   1.09 MB/s
distributed-1. 100% |############################################################################################| Time: 0:00:00 605.23 kB/s
Extracting packages ...
[      COMPLETE      ]|###############################################################################################################| 100%
Linking packages ...
Error: Error: post-link failed for: conda-forge::ipyparallel-5.1.1-py27_2##################################################           |  90%
$ conda -V
conda 4.1.6
```

**Comment by jakirkham** [comment]
So we added some post-link steps in PR ( https://github.com/conda-forge/ipyparallel-feedstock/pull/6 ) to ensure that one can use the IPython Clusters widget if the `notebook` is provided. However, it is not really ideal as we don't want to make the `notebook` a required dependency.

Ideally what we want is to make it an optional dependency and only run these post-link steps if that optional dependency will be satisfied. As there is no way to do this, we try to check and see if the `notebook` is available. If it is not, we do nothing (quietly). If it is available, we try to install the widget (quietly).

When simply installing `ipyparallel`, I don't have any post-link issues. When installing it with the `notebook`, I don't have any post-link issues. When following your example literally, I fail to reproduce the issue. However, it may be that this is a fixed bug in `conda`. I'm using version `4.1.11`. Could you please try updating `conda` and see if the problem still occurs?

**Comment by michaelaye** [comment]
I was using conda 4.1.11 in above linked conda/conda#3426 issue and was and still am seeing this error.

**Comment by michaelaye** [comment]
Shortest way for me to recreate:
1. conda create -n testing python=3
2. source activate testing
3. conda install ipyparallel

``` bash
(testing) └─❱❱❱ conda install ipyparallel                                             +6447 15:23 ❰─┘
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/klay6683/miniconda3/envs/testing:

The following NEW packages will be INSTALLED:

    appnope:                            0.1.0-py35_0
    backports.shutil_get_terminal_size: 1.0.0-py35_0  conda-forge
    decorator:                          4.0.10-py35_0 conda-forge
    ipykernel:                          4.5.0-py35_0  conda-forge
    ipyparallel:                        5.2.0-py35_0  conda-forge
    ipython:                            5.1.0-py35_0  conda-forge
    ipython_genutils:                   0.1.0-py35_0  conda-forge
    jupyter_client:                     4.4.0-py35_0  conda-forge
    jupyter_core:                       4.2.0-py35_0  conda-forge
    libsodium:                          1.0.10-0      conda-forge
    pexpect:                            4.2.1-py35_0  conda-forge
    pickleshare:                        0.7.3-py35_0  conda-forge
    prompt_toolkit:                     1.0.7-py35_0  conda-forge
    ptyprocess:                         0.5.1-py35_0  conda-forge
    pygments:                           2.1.3-py35_1  conda-forge
    python.app:                         1.2-py35_4
    pyzmq:                              15.4.0-py35_0 conda-forge
    simplegeneric:                      0.8.1-py35_0  conda-forge
    six:                                1.10.0-py35_0 conda-forge
    tornado:                            4.4.1-py35_1  conda-forge
    traitlets:                          4.3.0-py35_0  conda-forge
    wcwidth:                            0.1.7-py35_0  conda-forge
    zeromq:                             4.1.5-0       conda-forge

Proceed ([y]/n)? y

Linking packages ...
Error: Error: post-link failed for: conda-forge::ipyparallel-5.2.0-py35_0###################    |  95%
```

This with an activated conda-forge default obviously:

``` bash
(testing) └─❱❱❱ cat ~/.condarc                                                   1 ⏎  +6448 15:25 ❰─┘
channels:
  - conda-forge
  - defaults
```

**Comment by minrk** [comment]
When I run the same thing, everything works. Unfortunately, the output-suppression in the post-link script also hides any errors, making it difficult to diagnose.

Double-unfortunately, I noticed that all of the information gets sent to stderr, which I think it shouldn't. I think I have a better way to suppress the output, though.

**Comment by jakirkham** [comment]
So we can write to `$PREFIX/.messages.txt`, which should be displayed to us. Is that what you were thinking or did you have something else in mind?

xref: http://conda.pydata.org/docs/building/build-scripts.html

**Comment by jakirkham** [comment]
FWIW I tried to follow the steps above, @michaelaye , but I'm also unable to reproduce this. Maybe run `conda info`? Can you think of anything else that might be helpful for reproducing?

**Comment by jakirkham** [comment]
Put together PR ( https://github.com/conda-forge/ipyparallel-feedstock/pull/11 ), which should do exactly that.

**Comment by michaelaye** [comment]
Bizarre, also cannot reproduce it anymore, even so above failed install did not go away just by retry-ing. I tried both macOS and linux.

CORRECTION: I **CAN** reproduce it on linux, I just forgot that I already had removed conda-forge as default channel:

``` bash
jupyter_client 100% |##########################################| Time: 0:00:00   1.09 MB/s
prompt_toolkit 100% |##########################################| Time: 0:00:00   1.30 MB/s
ipython-5.1.0- 100% |##########################################| Time: 0:00:00   2.48 MB/s
ipykernel-4.5. 100% |##########################################| Time: 0:00:00   1.76 MB/s
ipyparallel-5. 100% |##########################################| Time: 0:00:00   1.77 MB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################| 100%
Linking packages ...
LinkError: Link error: Error: post-link failed for: conda-forge::ipyparallel-5.2.0-py35_0


(testing)
```

Here is `conda info` for the linux system:

``` bash
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : not installed
         python version : 3.4.5.final.0
       requests version : 2.11.1
       root environment : /usr/local/python/miniconda3  (writable)
    default environment : /usr/local/python/miniconda3
       envs directories : /usr/local/python/miniconda3/envs
          package cache : /usr/local/python/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/klay6683/.condarc
           offline mode : False
```

**Comment by michaelaye** [comment]
I cannot reproduce it on macOS.

**Comment by minrk** [comment]
A key feature of your test case is that the `notebook` package is not present in your env. That means that the likely error is caused by shelling out to `jupyter nbextension` _outside_ your env. If you regularly use conda, there's a good chance this was an old version that doesn't support the `--sys-prefix` and/or `--py` args.

**Comment by michaelaye** [comment]
The linux case above used today's version of conda, 4.2.9. though?

**Comment by minrk** [comment]
#12 should fix it if finding `jupyter nbextension` outside the env was the problem. It should also unhide error output when there are errors.

**Comment by michaelaye** [comment]
I redid my example while including `notebook` in the install command. Still the same error happens:

``` bash
$ conda install notebook ipyparallel
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /usr/local/python/miniconda3/envs/testing:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    entrypoints-0.2.2          |           py35_0           3 KB  conda-forge
    jsonschema-2.5.1           |           py35_0          58 KB  conda-forge
    markupsafe-0.23            |           py35_0          33 KB  conda-forge
    mistune-0.7.3              |           py35_0          22 KB  conda-forge
    terminado-0.6              |           py35_0          18 KB  conda-forge
    jinja2-2.8                 |           py35_1         278 KB  conda-forge
    nbformat-4.1.0             |           py35_0         326 KB  conda-forge
    nbconvert-4.2.0            |           py35_0         315 KB  conda-forge
    notebook-4.2.3             |           py35_0         5.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.7 MB

The following NEW packages will be INSTALLED:

    backports.shutil_get_terminal_size: 1.0.0-py35_0  conda-forge
    decorator:                          4.0.10-py35_0 conda-forge
    entrypoints:                        0.2.2-py35_0  conda-forge
    ipykernel:                          4.5.0-py35_0  conda-forge
    ipyparallel:                        5.2.0-py35_0  conda-forge
    ipython:                            5.1.0-py35_0  conda-forge
    ipython_genutils:                   0.1.0-py35_0  conda-forge
    jinja2:                             2.8-py35_1    conda-forge
    jsonschema:                         2.5.1-py35_0  conda-forge
    jupyter_client:                     4.4.0-py35_0  conda-forge
    jupyter_core:                       4.2.0-py35_0  conda-forge
    libsodium:                          1.0.10-0      conda-forge
    markupsafe:                         0.23-py35_0   conda-forge
    mistune:                            0.7.3-py35_0  conda-forge
    nbconvert:                          4.2.0-py35_0  conda-forge
    nbformat:                           4.1.0-py35_0  conda-forge
    notebook:                           4.2.3-py35_0  conda-forge
    pexpect:                            4.2.1-py35_0  conda-forge
    pickleshare:                        0.7.3-py35_0  conda-forge
    prompt_toolkit:                     1.0.7-py35_0  conda-forge
    ptyprocess:                         0.5.1-py35_0  conda-forge
    pygments:                           2.1.3-py35_1  conda-forge
    pyzmq:                              15.4.0-py35_0 conda-forge
    simplegeneric:                      0.8.1-py35_0  conda-forge
    six:                                1.10.0-py35_0 conda-forge
    terminado:                          0.6-py35_0    conda-forge
    tornado:                            4.4.1-py35_1  conda-forge
    traitlets:                          4.3.0-py35_0  conda-forge
    wcwidth:                            0.1.7-py35_0  conda-forge
    zeromq:                             4.1.5-0       conda-forge

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
entrypoints-0. 100% |############################################################################| Time: 0:00:00   3.07 MB/s
jsonschema-2.5 100% |############################################################################| Time: 0:00:00 482.52 kB/s
markupsafe-0.2 100% |############################################################################| Time: 0:00:00 417.63 kB/s
mistune-0.7.3- 100% |############################################################################| Time: 0:00:00 553.76 kB/s
terminado-0.6- 100% |############################################################################| Time: 0:00:00 443.49 kB/s
jinja2-2.8-py3 100% |############################################################################| Time: 0:00:00 981.56 kB/s
nbformat-4.1.0 100% |############################################################################| Time: 0:00:00 410.17 kB/s
nbconvert-4.2. 100% |############################################################################| Time: 0:00:00 599.49 kB/s
notebook-4.2.3 100% |############################################################################| Time: 0:00:01   5.46 MB/s
Extracting packages ...
[      COMPLETE      ]|###############################################################################################| 100%
Linking packages ...
LinkError: Link error: Error: post-link failed for: conda-forge::ipyparallel-5.2.0-py35_0 #####################       |  93%
```

I'm not sure if that is what you meant, @minrk .

**Comment by jakirkham** [comment]
Yeah, the problem is we don't have any control of _which order_ the `notebook` and `ipyparallel` get installed in. As a result, this case could be exactly the same as before. I think to accomplish what @minrk suggested you would need to install the `notebook` first in one step and then install `ipyparallel` in a following step.

 If we could have optional dependency support in `conda`/`conda-build` ( https://github.com/conda/conda/issues/3299 ), we could probably do something smarter with that link script.

**Comment by michaelaye** [comment]
I confirm that this procedure does not produce the linking error on linux:
1. `conda create -n testing python=3`
2. `source activate testing`
3. `conda install notebook`
4. `conda install ipyparallel`

thanks for the info!

**Comment by jakirkham** [comment]
Just merged PR ( https://github.com/conda-forge/ipyparallel-feedstock/pull/12 ) and CIs have generated some new packages from it. Please give them a try and let us know how it goes. At a bare minimum, it should give us more info to use in debugging if nothing else.

**Comment by jakirkham** [comment]
This issue has been quiet for a while. Guessing PR ( https://github.com/conda-forge/ipyparallel-feedstock/pull/12 ) fixed. As such am closing this out. If you are still having this issue, please provide details about your current setup and we can reopen. Thanks.

**Comment by michaelaye** [comment]
I confirm that a conda-forge install on linux does also not show this error anymore.

**Comment by ijstokes** [comment]
@kalefranz there is some useful info here for error reporting that you might want to consider, or may already be addressed by recent `conda` and `conda-build` releases.

**Comment by jakirkham** [comment]
Thanks for confirming, @michaelaye.
